	.balign 4
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.balign 4
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.balign 4
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.balign 4
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.balign 4
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.balign 4
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.balign 4
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.balign 4
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.balign 4
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.balign 4
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.balign 4
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.balign 4
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.balign 4
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.balign 4
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.balign 4
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.balign 4
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.balign 4
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.balign 4
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.balign 4
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.balign 4
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.balign 4
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.balign 4
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.balign 4
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.balign 4
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.balign 4
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.balign 4
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.balign 4
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.balign 4
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.balign 4
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.balign 4
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.balign 4
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.balign 4
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.balign 4
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.balign 4
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.balign 4
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.balign 4
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.balign 4
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.balign 4
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.balign 4
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.balign 4
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.balign 4
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.balign 4
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.balign 4
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.balign 4
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.balign 4
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.balign 4
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.balign 4
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.balign 4
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.balign 4
DirectSoundWaveData_sc88pro_tuba_39:: /*N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up*/
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.balign 4
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.balign 4
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.balign 4
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.balign 4
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.balign 4
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.balign 4
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.balign 4
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.balign 4
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.balign 4
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.balign 4
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.balign 4
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.balign 4
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.balign 4
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.balign 4
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.balign 4
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.balign 4
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.balign 4
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.balign 4
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.balign 4
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.balign 4
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.balign 4
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.balign 4
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.balign 4
DirectSoundWaveData_unknown_1::
	.incbin "sound/direct_sound_samples/unknown_01.bin"

	.balign 4
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.balign 4
DirectSoundWaveData_unknown_2::
	.incbin "sound/direct_sound_samples/unknown_02.bin"

	.balign 4
DirectSoundWaveData_unknown_3::
	.incbin "sound/direct_sound_samples/unknown_03.bin"

	.balign 4
DirectSoundWaveData_unknown_4::
	.incbin "sound/direct_sound_samples/unknown_04.bin"

	.balign 4
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.balign 4
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.balign 4
DirectSoundWaveData_unknown_5::
	.incbin "sound/direct_sound_samples/unknown_05.bin"

	.balign 4
DirectSoundWaveData_unknown_6::
	.incbin "sound/direct_sound_samples/unknown_06.bin"

	.balign 4
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.balign 4
DirectSoundWaveData_unknown_7::
	.incbin "sound/direct_sound_samples/unknown_07.bin"

	.balign 4
DirectSoundWaveData_unknown_8::
	.incbin "sound/direct_sound_samples/unknown_08.bin"

	.balign 4
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.balign 4
DirectSoundWaveData_unknown_9::
	.incbin "sound/direct_sound_samples/unknown_09.bin"

	.balign 4
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.balign 4
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.balign 4
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.balign 4
DirectSoundWaveData_unknown_10::
	.incbin "sound/direct_sound_samples/unknown_10.bin"

	.balign 4
DirectSoundWaveData_unknown_11::
	.incbin "sound/direct_sound_samples/unknown_11.bin"

	.balign 4
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.balign 4
DirectSoundWaveData_unknown_12::
	.incbin "sound/direct_sound_samples/unknown_12.bin"

	.balign 4
DirectSoundWaveData_unknown_13::
	.incbin "sound/direct_sound_samples/unknown_13.bin"

	.balign 4
DirectSoundWaveData_unknown_14::
	.incbin "sound/direct_sound_samples/unknown_14.bin"

	.balign 4
DirectSoundWaveData_unknown_15::
	.incbin "sound/direct_sound_samples/unknown_15.bin"

	.balign 4
DirectSoundWaveData_unknown_16::
	.incbin "sound/direct_sound_samples/unknown_16.bin"

	.balign 4
DirectSoundWaveData_unknown_17::
	.incbin "sound/direct_sound_samples/unknown_17.bin"

	.balign 4
Cry_Bulbasaur::
	.incbin "sound/direct_sound_samples/cries/bulbasaur.bin"

	.balign 4
Cry_Ivysaur::
	.incbin "sound/direct_sound_samples/cries/ivysaur.bin"

	.balign 4
Cry_Venusaur::
	.incbin "sound/direct_sound_samples/cries/venusaur.bin"

	.balign 4
Cry_Charmander::
	.incbin "sound/direct_sound_samples/cries/charmander.bin"

	.balign 4
Cry_Charmeleon::
	.incbin "sound/direct_sound_samples/cries/charmeleon.bin"

	.balign 4
Cry_Charizard::
	.incbin "sound/direct_sound_samples/cries/charizard.bin"

	.balign 4
Cry_Squirtle::
	.incbin "sound/direct_sound_samples/cries/squirtle.bin"

	.balign 4
Cry_Wartortle::
	.incbin "sound/direct_sound_samples/cries/wartortle.bin"

	.balign 4
Cry_Blastoise::
	.incbin "sound/direct_sound_samples/cries/blastoise.bin"

	.balign 4
Cry_Caterpie::
	.incbin "sound/direct_sound_samples/cries/caterpie.bin"

	.balign 4
Cry_Metapod::
	.incbin "sound/direct_sound_samples/cries/metapod.bin"

	.balign 4
Cry_Butterfree::
	.incbin "sound/direct_sound_samples/cries/butterfree.bin"

	.balign 4
Cry_Weedle::
	.incbin "sound/direct_sound_samples/cries/weedle.bin"

	.balign 4
Cry_Kakuna::
	.incbin "sound/direct_sound_samples/cries/kakuna.bin"

	.balign 4
Cry_Beedrill::
	.incbin "sound/direct_sound_samples/cries/beedrill.bin"

	.balign 4
Cry_Pidgey::
	.incbin "sound/direct_sound_samples/cries/pidgey.bin"

	.balign 4
Cry_Pidgeotto::
	.incbin "sound/direct_sound_samples/cries/pidgeotto.bin"

	.balign 4
Cry_Pidgeot::
	.incbin "sound/direct_sound_samples/cries/pidgeot.bin"

	.balign 4
Cry_Rattata::
	.incbin "sound/direct_sound_samples/cries/rattata.bin"

	.balign 4
Cry_Raticate::
	.incbin "sound/direct_sound_samples/cries/raticate.bin"

	.balign 4
Cry_Spearow::
	.incbin "sound/direct_sound_samples/cries/spearow.bin"

	.balign 4
Cry_Fearow::
	.incbin "sound/direct_sound_samples/cries/fearow.bin"

	.balign 4
Cry_Ekans::
	.incbin "sound/direct_sound_samples/cries/ekans.bin"

	.balign 4
Cry_Arbok::
	.incbin "sound/direct_sound_samples/cries/arbok.bin"

	.balign 4
Cry_Pikachu::
	.incbin "sound/direct_sound_samples/cries/pikachu.bin"

	.balign 4
Cry_Raichu::
	.incbin "sound/direct_sound_samples/cries/raichu.bin"

	.balign 4
Cry_Sandshrew::
	.incbin "sound/direct_sound_samples/cries/sandshrew.bin"

	.balign 4
Cry_Sandslash::
	.incbin "sound/direct_sound_samples/cries/sandslash.bin"

	.balign 4
Cry_NidoranF::
	.incbin "sound/direct_sound_samples/cries/nidoran_f.bin"

	.balign 4
Cry_Nidorina::
	.incbin "sound/direct_sound_samples/cries/nidorina.bin"

	.balign 4
Cry_Nidoqueen::
	.incbin "sound/direct_sound_samples/cries/nidoqueen.bin"

	.balign 4
Cry_NidoranM::
	.incbin "sound/direct_sound_samples/cries/nidoran_m.bin"

	.balign 4
Cry_Nidorino::
	.incbin "sound/direct_sound_samples/cries/nidorino.bin"

	.balign 4
Cry_Nidoking::
	.incbin "sound/direct_sound_samples/cries/nidoking.bin"

	.balign 4
Cry_Clefairy::
	.incbin "sound/direct_sound_samples/cries/clefairy.bin"

	.balign 4
Cry_Clefable::
	.incbin "sound/direct_sound_samples/cries/clefable.bin"

	.balign 4
Cry_Vulpix::
	.incbin "sound/direct_sound_samples/cries/vulpix.bin"

	.balign 4
Cry_Ninetales::
	.incbin "sound/direct_sound_samples/cries/ninetales.bin"

	.balign 4
Cry_Jigglypuff::
	.incbin "sound/direct_sound_samples/cries/jigglypuff.bin"

	.balign 4
Cry_Wigglytuff::
	.incbin "sound/direct_sound_samples/cries/wigglytuff.bin"

	.balign 4
Cry_Zubat::
	.incbin "sound/direct_sound_samples/cries/zubat.bin"

	.balign 4
Cry_Golbat::
	.incbin "sound/direct_sound_samples/cries/golbat.bin"

	.balign 4
Cry_Oddish::
	.incbin "sound/direct_sound_samples/cries/oddish.bin"

	.balign 4
Cry_Gloom::
	.incbin "sound/direct_sound_samples/cries/gloom.bin"

	.balign 4
Cry_Vileplume::
	.incbin "sound/direct_sound_samples/cries/vileplume.bin"

	.balign 4
Cry_Paras::
	.incbin "sound/direct_sound_samples/cries/paras.bin"

	.balign 4
Cry_Parasect::
	.incbin "sound/direct_sound_samples/cries/parasect.bin"

	.balign 4
Cry_Venonat::
	.incbin "sound/direct_sound_samples/cries/venonat.bin"

	.balign 4
Cry_Venomoth::
	.incbin "sound/direct_sound_samples/cries/venomoth.bin"

	.balign 4
Cry_Diglett::
	.incbin "sound/direct_sound_samples/cries/diglett.bin"

	.balign 4
Cry_Dugtrio::
	.incbin "sound/direct_sound_samples/cries/dugtrio.bin"

	.balign 4
Cry_Meowth::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.balign 4
Cry_Persian::
	.incbin "sound/direct_sound_samples/cries/persian.bin"

	.balign 4
Cry_Psyduck::
	.incbin "sound/direct_sound_samples/cries/psyduck.bin"

	.balign 4
Cry_Golduck::
	.incbin "sound/direct_sound_samples/cries/golduck.bin"

	.balign 4
Cry_Mankey::
	.incbin "sound/direct_sound_samples/cries/mankey.bin"

	.balign 4
Cry_Primeape::
	.incbin "sound/direct_sound_samples/cries/primeape.bin"

	.balign 4
Cry_Growlithe::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.balign 4
Cry_Arcanine::
	.incbin "sound/direct_sound_samples/cries/arcanine.bin"

	.balign 4
Cry_Poliwag::
	.incbin "sound/direct_sound_samples/cries/poliwag.bin"

	.balign 4
Cry_Poliwhirl::
	.incbin "sound/direct_sound_samples/cries/poliwhirl.bin"

	.balign 4
Cry_Poliwrath::
	.incbin "sound/direct_sound_samples/cries/poliwrath.bin"

	.balign 4
Cry_Abra::
	.incbin "sound/direct_sound_samples/cries/abra.bin"

	.balign 4
Cry_Kadabra::
	.incbin "sound/direct_sound_samples/cries/kadabra.bin"

	.balign 4
Cry_Alakazam::
	.incbin "sound/direct_sound_samples/cries/alakazam.bin"

	.balign 4
Cry_Machop::
	.incbin "sound/direct_sound_samples/cries/machop.bin"

	.balign 4
Cry_Machoke::
	.incbin "sound/direct_sound_samples/cries/machoke.bin"

	.balign 4
Cry_Machamp::
	.incbin "sound/direct_sound_samples/cries/machamp.bin"

	.balign 4
Cry_Bellsprout::
	.incbin "sound/direct_sound_samples/cries/bellsprout.bin"

	.balign 4
Cry_Weepinbell::
	.incbin "sound/direct_sound_samples/cries/weepinbell.bin"

	.balign 4
Cry_Victreebel::
	.incbin "sound/direct_sound_samples/cries/victreebel.bin"

	.balign 4
Cry_Tentacool::
	.incbin "sound/direct_sound_samples/cries/tentacool.bin"

	.balign 4
Cry_Tentacruel::
	.incbin "sound/direct_sound_samples/cries/tentacruel.bin"

	.balign 4
Cry_Geodude::
	.incbin "sound/direct_sound_samples/cries/geodude.bin"

	.balign 4
Cry_Graveler::
	.incbin "sound/direct_sound_samples/cries/graveler.bin"

	.balign 4
Cry_Golem::
	.incbin "sound/direct_sound_samples/cries/golem.bin"

	.balign 4
Cry_Ponyta::
	.incbin "sound/direct_sound_samples/cries/ponyta.bin"

	.balign 4
Cry_Rapidash::
	.incbin "sound/direct_sound_samples/cries/rapidash.bin"

	.balign 4
Cry_Slowpoke::
	.incbin "sound/direct_sound_samples/cries/slowpoke.bin"

	.balign 4
Cry_Slowbro::
	.incbin "sound/direct_sound_samples/cries/slowbro.bin"

	.balign 4
Cry_Magnemite::
	.incbin "sound/direct_sound_samples/cries/magnemite.bin"

	.balign 4
Cry_Magneton::
	.incbin "sound/direct_sound_samples/cries/magneton.bin"

	.balign 4
Cry_Farfetchd::
	.incbin "sound/direct_sound_samples/cries/farfetchd.bin"

	.balign 4
Cry_Doduo::
	.incbin "sound/direct_sound_samples/cries/doduo.bin"

	.balign 4
Cry_Dodrio::
	.incbin "sound/direct_sound_samples/cries/dodrio.bin"

	.balign 4
Cry_Seel::
	.incbin "sound/direct_sound_samples/cries/seel.bin"

	.balign 4
Cry_Dewgong::
	.incbin "sound/direct_sound_samples/cries/dewgong.bin"

	.balign 4
Cry_Grimer::
	.incbin "sound/direct_sound_samples/cries/grimer.bin"

	.balign 4
Cry_Muk::
	.incbin "sound/direct_sound_samples/cries/muk.bin"

	.balign 4
Cry_Shellder::
	.incbin "sound/direct_sound_samples/cries/shellder.bin"

	.balign 4
Cry_Cloyster::
	.incbin "sound/direct_sound_samples/cries/cloyster.bin"

	.balign 4
Cry_Gastly::
	.incbin "sound/direct_sound_samples/cries/gastly.bin"

	.balign 4
Cry_Haunter::
	.incbin "sound/direct_sound_samples/cries/haunter.bin"

	.balign 4
Cry_Gengar::
	.incbin "sound/direct_sound_samples/cries/gengar.bin"

	.balign 4
Cry_Onix::
	.incbin "sound/direct_sound_samples/cries/onix.bin"

	.balign 4
Cry_Drowzee::
	.incbin "sound/direct_sound_samples/cries/drowzee.bin"

	.balign 4
Cry_Hypno::
	.incbin "sound/direct_sound_samples/cries/hypno.bin"

	.balign 4
Cry_Krabby::
	.incbin "sound/direct_sound_samples/cries/krabby.bin"

	.balign 4
Cry_Kingler::
	.incbin "sound/direct_sound_samples/cries/kingler.bin"

	.balign 4
Cry_Voltorb::
	.incbin "sound/direct_sound_samples/cries/voltorb.bin"

	.balign 4
Cry_Electrode::
	.incbin "sound/direct_sound_samples/cries/electrode.bin"

	.balign 4
Cry_Exeggcute::
	.incbin "sound/direct_sound_samples/cries/exeggcute.bin"

	.balign 4
Cry_Exeggutor::
	.incbin "sound/direct_sound_samples/cries/exeggutor.bin"

	.balign 4
Cry_Cubone::
	.incbin "sound/direct_sound_samples/cries/cubone.bin"

	.balign 4
Cry_Marowak::
	.incbin "sound/direct_sound_samples/cries/marowak.bin"

	.balign 4
Cry_Hitmonlee::
	.incbin "sound/direct_sound_samples/cries/hitmonlee.bin"

	.balign 4
Cry_Hitmonchan::
	.incbin "sound/direct_sound_samples/cries/hitmonchan.bin"

	.balign 4
Cry_Lickitung::
	.incbin "sound/direct_sound_samples/cries/lickitung.bin"

	.balign 4
Cry_Koffing::
	.incbin "sound/direct_sound_samples/cries/koffing.bin"

	.balign 4
Cry_Weezing::
	.incbin "sound/direct_sound_samples/cries/weezing.bin"

	.balign 4
Cry_Rhyhorn::
	.incbin "sound/direct_sound_samples/cries/rhyhorn.bin"

	.balign 4
Cry_Rhydon::
	.incbin "sound/direct_sound_samples/cries/rhydon.bin"

	.balign 4
Cry_Chansey::
	.incbin "sound/direct_sound_samples/cries/chansey.bin"

	.balign 4
Cry_Tangela::
	.incbin "sound/direct_sound_samples/cries/tangela.bin"

	.balign 4
Cry_Kangaskhan::
	.incbin "sound/direct_sound_samples/cries/kangaskhan.bin"

	.balign 4
Cry_Horsea::
	.incbin "sound/direct_sound_samples/cries/horsea.bin"

	.balign 4
Cry_Seadra::
	.incbin "sound/direct_sound_samples/cries/seadra.bin"

	.balign 4
Cry_Goldeen::
	.incbin "sound/direct_sound_samples/cries/goldeen.bin"

	.balign 4
Cry_Seaking::
	.incbin "sound/direct_sound_samples/cries/seaking.bin"

	.balign 4
Cry_Staryu::
	.incbin "sound/direct_sound_samples/cries/staryu.bin"

	.balign 4
Cry_Starmie::
	.incbin "sound/direct_sound_samples/cries/starmie.bin"

	.balign 4
Cry_MrMime::
	.incbin "sound/direct_sound_samples/cries/mr_mime.bin"

	.balign 4
Cry_Scyther::
	.incbin "sound/direct_sound_samples/cries/scyther.bin"

	.balign 4
Cry_Jynx::
	.incbin "sound/direct_sound_samples/cries/jynx.bin"

	.balign 4
Cry_Electabuzz::
	.incbin "sound/direct_sound_samples/cries/electabuzz.bin"

	.balign 4
Cry_Magmar::
	.incbin "sound/direct_sound_samples/cries/magmar.bin"

	.balign 4
Cry_Pinsir::
	.incbin "sound/direct_sound_samples/cries/pinsir.bin"

	.balign 4
Cry_Tauros::
	.incbin "sound/direct_sound_samples/cries/tauros.bin"

	.balign 4
Cry_Magikarp::
	.incbin "sound/direct_sound_samples/cries/magikarp.bin"

	.balign 4
Cry_Gyarados::
	.incbin "sound/direct_sound_samples/cries/gyarados.bin"

	.balign 4
Cry_Lapras::
	.incbin "sound/direct_sound_samples/cries/lapras.bin"

	.balign 4
Cry_Ditto::
	.incbin "sound/direct_sound_samples/cries/ditto.bin"

	.balign 4
Cry_Eevee::
	.incbin "sound/direct_sound_samples/cries/eevee.bin"

	.balign 4
Cry_Vaporeon::
	.incbin "sound/direct_sound_samples/cries/vaporeon.bin"

	.balign 4
Cry_Jolteon::
	.incbin "sound/direct_sound_samples/cries/jolteon.bin"

	.balign 4
Cry_Flareon::
	.incbin "sound/direct_sound_samples/cries/flareon.bin"

	.balign 4
Cry_Porygon::
	.incbin "sound/direct_sound_samples/cries/porygon.bin"

	.balign 4
Cry_Omanyte::
	.incbin "sound/direct_sound_samples/cries/omanyte.bin"

	.balign 4
Cry_Omastar::
	.incbin "sound/direct_sound_samples/cries/omastar.bin"

	.balign 4
Cry_Kabuto::
	.incbin "sound/direct_sound_samples/cries/kabuto.bin"

	.balign 4
Cry_Kabutops::
	.incbin "sound/direct_sound_samples/cries/kabutops.bin"

	.balign 4
Cry_Aerodactyl::
	.incbin "sound/direct_sound_samples/cries/aerodactyl.bin"

	.balign 4
Cry_Snorlax::
	.incbin "sound/direct_sound_samples/cries/snorlax.bin"

	.balign 4
Cry_Articuno::
	.incbin "sound/direct_sound_samples/cries/articuno.bin"

	.balign 4
Cry_Zapdos::
	.incbin "sound/direct_sound_samples/cries/zapdos.bin"

	.balign 4
Cry_Moltres::
	.incbin "sound/direct_sound_samples/cries/moltres.bin"

	.balign 4
Cry_Dratini::
	.incbin "sound/direct_sound_samples/cries/dratini.bin"

	.balign 4
Cry_Dragonair::
	.incbin "sound/direct_sound_samples/cries/dragonair.bin"

	.balign 4
Cry_Dragonite::
	.incbin "sound/direct_sound_samples/cries/dragonite.bin"

	.balign 4
Cry_Mewtwo::
	.incbin "sound/direct_sound_samples/cries/mewtwo.bin"

	.balign 4
Cry_Mew::
	.incbin "sound/direct_sound_samples/cries/mew.bin"

	.balign 4
Cry_Chikorita::
	.incbin "sound/direct_sound_samples/cries/chikorita.bin"

	.balign 4
Cry_Bayleef::
	.incbin "sound/direct_sound_samples/cries/bayleef.bin"

	.balign 4
Cry_Meganium::
	.incbin "sound/direct_sound_samples/cries/meganium.bin"

	.balign 4
Cry_Cyndaquil::
	.incbin "sound/direct_sound_samples/cries/cyndaquil.bin"

	.balign 4
Cry_Quilava::
	.incbin "sound/direct_sound_samples/cries/quilava.bin"

	.balign 4
Cry_Typhlosion::
	.incbin "sound/direct_sound_samples/cries/typhlosion.bin"

	.balign 4
Cry_Totodile::
	.incbin "sound/direct_sound_samples/cries/totodile.bin"

	.balign 4
Cry_Croconaw::
	.incbin "sound/direct_sound_samples/cries/croconaw.bin"

	.balign 4
Cry_Feraligatr::
	.incbin "sound/direct_sound_samples/cries/feraligatr.bin"

	.balign 4
Cry_Sentret::
	.incbin "sound/direct_sound_samples/cries/sentret.bin"

	.balign 4
Cry_Furret::
	.incbin "sound/direct_sound_samples/cries/furret.bin"

	.balign 4
Cry_Hoothoot::
	.incbin "sound/direct_sound_samples/cries/hoothoot.bin"

	.balign 4
Cry_Noctowl::
	.incbin "sound/direct_sound_samples/cries/noctowl.bin"

	.balign 4
Cry_Ledyba::
	.incbin "sound/direct_sound_samples/cries/ledyba.bin"

	.balign 4
Cry_Ledian::
	.incbin "sound/direct_sound_samples/cries/ledian.bin"

	.balign 4
Cry_Spinarak::
	.incbin "sound/direct_sound_samples/cries/spinarak.bin"

	.balign 4
Cry_Ariados::
	.incbin "sound/direct_sound_samples/cries/ariados.bin"

	.balign 4
Cry_Crobat::
	.incbin "sound/direct_sound_samples/cries/crobat.bin"

	.balign 4
Cry_Chinchou::
	.incbin "sound/direct_sound_samples/cries/chinchou.bin"

	.balign 4
Cry_Lanturn::
	.incbin "sound/direct_sound_samples/cries/lanturn.bin"

	.balign 4
Cry_Pichu::
	.incbin "sound/direct_sound_samples/cries/pichu.bin"

	.balign 4
Cry_Cleffa::
	.incbin "sound/direct_sound_samples/cries/cleffa.bin"

	.balign 4
Cry_Igglybuff::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.balign 4
Cry_Togepi::
	.incbin "sound/direct_sound_samples/cries/togepi.bin"

	.balign 4
Cry_Togetic::
	.incbin "sound/direct_sound_samples/cries/togetic.bin"

	.balign 4
Cry_Natu::
	.incbin "sound/direct_sound_samples/cries/natu.bin"

	.balign 4
Cry_Xatu::
	.incbin "sound/direct_sound_samples/cries/xatu.bin"

	.balign 4
Cry_Mareep::
	.incbin "sound/direct_sound_samples/cries/mareep.bin"

	.balign 4
Cry_Flaaffy::
	.incbin "sound/direct_sound_samples/cries/flaaffy.bin"

	.balign 4
Cry_Ampharos::
	.incbin "sound/direct_sound_samples/cries/ampharos.bin"

	.balign 4
Cry_Bellossom::
	.incbin "sound/direct_sound_samples/cries/bellossom.bin"

	.balign 4
Cry_Marill::
	.incbin "sound/direct_sound_samples/cries/marill.bin"

	.balign 4
Cry_Azumarill::
	.incbin "sound/direct_sound_samples/cries/azumarill.bin"

	.balign 4
Cry_Sudowoodo::
	.incbin "sound/direct_sound_samples/cries/sudowoodo.bin"

	.balign 4
Cry_Politoed::
	.incbin "sound/direct_sound_samples/cries/politoed.bin"

	.balign 4
Cry_Hoppip::
	.incbin "sound/direct_sound_samples/cries/hoppip.bin"

	.balign 4
Cry_Skiploom::
	.incbin "sound/direct_sound_samples/cries/skiploom.bin"

	.balign 4
Cry_Jumpluff::
	.incbin "sound/direct_sound_samples/cries/jumpluff.bin"

	.balign 4
Cry_Aipom::
	.incbin "sound/direct_sound_samples/cries/aipom.bin"

	.balign 4
Cry_Sunkern::
	.incbin "sound/direct_sound_samples/cries/sunkern.bin"

	.balign 4
Cry_Sunflora::
	.incbin "sound/direct_sound_samples/cries/sunflora.bin"

	.balign 4
Cry_Yanma::
	.incbin "sound/direct_sound_samples/cries/yanma.bin"

	.balign 4
Cry_Wooper::
	.incbin "sound/direct_sound_samples/cries/wooper.bin"

	.balign 4
Cry_Quagsire::
	.incbin "sound/direct_sound_samples/cries/quagsire.bin"

	.balign 4
Cry_Espeon::
	.incbin "sound/direct_sound_samples/cries/espeon.bin"

	.balign 4
Cry_Umbreon::
	.incbin "sound/direct_sound_samples/cries/umbreon.bin"

	.balign 4
Cry_Murkrow::
	.incbin "sound/direct_sound_samples/cries/murkrow.bin"

	.balign 4
Cry_Slowking::
	.incbin "sound/direct_sound_samples/cries/slowking.bin"

	.balign 4
Cry_Misdreavus::
	.incbin "sound/direct_sound_samples/cries/misdreavus.bin"

	.balign 4
Cry_Unown::
	.incbin "sound/direct_sound_samples/cries/unown.bin"

	.balign 4
Cry_Wobbuffet::
	.incbin "sound/direct_sound_samples/cries/wobbuffet.bin"

	.balign 4
Cry_Girafarig::
	.incbin "sound/direct_sound_samples/cries/girafarig.bin"

	.balign 4
Cry_Pineco::
	.incbin "sound/direct_sound_samples/cries/pineco.bin"

	.balign 4
Cry_Forretress::
	.incbin "sound/direct_sound_samples/cries/forretress.bin"

	.balign 4
Cry_Dunsparce::
	.incbin "sound/direct_sound_samples/cries/dunsparce.bin"

	.balign 4
Cry_Gligar::
	.incbin "sound/direct_sound_samples/cries/gligar.bin"

	.balign 4
Cry_Steelix::
	.incbin "sound/direct_sound_samples/cries/steelix.bin"

	.balign 4
Cry_Snubbull::
	.incbin "sound/direct_sound_samples/cries/snubbull.bin"

	.balign 4
Cry_Granbull::
	.incbin "sound/direct_sound_samples/cries/granbull.bin"

	.balign 4
Cry_Qwilfish::
	.incbin "sound/direct_sound_samples/cries/qwilfish.bin"

	.balign 4
Cry_Scizor::
	.incbin "sound/direct_sound_samples/cries/scizor.bin"

	.balign 4
Cry_Shuckle::
	.incbin "sound/direct_sound_samples/cries/shuckle.bin"

	.balign 4
Cry_Heracross::
	.incbin "sound/direct_sound_samples/cries/heracross.bin"

	.balign 4
Cry_Sneasel::
	.incbin "sound/direct_sound_samples/cries/sneasel.bin"

	.balign 4
Cry_Teddiursa::
	.incbin "sound/direct_sound_samples/cries/teddiursa.bin"

	.balign 4
Cry_Ursaring::
	.incbin "sound/direct_sound_samples/cries/ursaring.bin"

	.balign 4
Cry_Slugma::
	.incbin "sound/direct_sound_samples/cries/slugma.bin"

	.balign 4
Cry_Magcargo::
	.incbin "sound/direct_sound_samples/cries/magcargo.bin"

	.balign 4
Cry_Swinub::
	.incbin "sound/direct_sound_samples/cries/swinub.bin"

	.balign 4
Cry_Piloswine::
	.incbin "sound/direct_sound_samples/cries/piloswine.bin"

	.balign 4
Cry_Corsola::
	.incbin "sound/direct_sound_samples/cries/corsola.bin"

	.balign 4
Cry_Remoraid::
	.incbin "sound/direct_sound_samples/cries/remoraid.bin"

	.balign 4
Cry_Octillery::
	.incbin "sound/direct_sound_samples/cries/octillery.bin"

	.balign 4
Cry_Delibird::
	.incbin "sound/direct_sound_samples/cries/delibird.bin"

	.balign 4
Cry_Mantine::
	.incbin "sound/direct_sound_samples/cries/mantine.bin"

	.balign 4
Cry_Skarmory::
	.incbin "sound/direct_sound_samples/cries/skarmory.bin"

	.balign 4
Cry_Houndour::
	.incbin "sound/direct_sound_samples/cries/houndour.bin"

	.balign 4
Cry_Houndoom::
	.incbin "sound/direct_sound_samples/cries/houndoom.bin"

	.balign 4
Cry_Kingdra::
	.incbin "sound/direct_sound_samples/cries/kingdra.bin"

	.balign 4
Cry_Phanpy::
	.incbin "sound/direct_sound_samples/cries/phanpy.bin"

	.balign 4
Cry_Donphan::
	.incbin "sound/direct_sound_samples/cries/donphan.bin"

	.balign 4
Cry_Porygon2::
	.incbin "sound/direct_sound_samples/cries/porygon2.bin"

	.balign 4
Cry_Stantler::
	.incbin "sound/direct_sound_samples/cries/stantler.bin"

	.balign 4
Cry_Smeargle::
	.incbin "sound/direct_sound_samples/cries/smeargle.bin"

	.balign 4
Cry_Tyrogue::
	.incbin "sound/direct_sound_samples/cries/tyrogue.bin"

	.balign 4
Cry_Hitmontop::
	.incbin "sound/direct_sound_samples/cries/hitmontop.bin"

	.balign 4
Cry_Smoochum::
	.incbin "sound/direct_sound_samples/cries/smoochum.bin"

	.balign 4
Cry_Elekid::
	.incbin "sound/direct_sound_samples/cries/elekid.bin"

	.balign 4
Cry_Magby::
	.incbin "sound/direct_sound_samples/cries/magby.bin"

	.balign 4
Cry_Miltank::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.balign 4
Cry_Blissey::
	.incbin "sound/direct_sound_samples/cries/blissey.bin"

	.balign 4
Cry_Raikou::
	.incbin "sound/direct_sound_samples/cries/raikou.bin"

	.balign 4
Cry_Entei::
	.incbin "sound/direct_sound_samples/cries/entei.bin"

	.balign 4
Cry_Suicune::
	.incbin "sound/direct_sound_samples/cries/suicune.bin"

	.balign 4
Cry_Larvitar::
	.incbin "sound/direct_sound_samples/cries/larvitar.bin"

	.balign 4
Cry_Pupitar::
	.incbin "sound/direct_sound_samples/cries/pupitar.bin"

	.balign 4
Cry_Tyranitar::
	.incbin "sound/direct_sound_samples/cries/tyranitar.bin"

	.balign 4
Cry_Lugia::
	.incbin "sound/direct_sound_samples/cries/lugia.bin"

	.balign 4
Cry_HoOh::
	.incbin "sound/direct_sound_samples/cries/ho_oh.bin"

	.balign 4
Cry_Celebi::
	.incbin "sound/direct_sound_samples/cries/celebi.bin"

	.balign 4
Cry_Kecleon::
	.incbin "sound/direct_sound_samples/cries/kecleon.bin"

	.balign 4
Cry_Roselia::
	.incbin "sound/direct_sound_samples/cries/roselia.bin"

	.balign 4
Cry_Torkoal::
	.incbin "sound/direct_sound_samples/cries/torkoal.bin"

	.balign 4
Cry_Electrike::
	.incbin "sound/direct_sound_samples/cries/electrike.bin"

	.balign 4
Cry_Manectric::
	.incbin "sound/direct_sound_samples/cries/manectric.bin"

	.balign 4
Cry_Duskull::
	.incbin "sound/direct_sound_samples/cries/duskull.bin"

	.balign 4
Cry_Latias::
	.incbin "sound/direct_sound_samples/cries/latias.bin"

	.balign 4
Cry_Wynaut::
	.incbin "sound/direct_sound_samples/cries/wynaut.bin"

	.balign 4
Cry_Seviper::
	.incbin "sound/direct_sound_samples/cries/seviper.bin"

	.balign 4
Cry_Sharpedo::
	.incbin "sound/direct_sound_samples/cries/sharpedo.bin"

	.balign 4
Cry_Zangoose::
	.incbin "sound/direct_sound_samples/cries/zangoose.bin"

	.balign 4
Cry_Azurill::
	.incbin "sound/direct_sound_samples/cries/azurill.bin"

	.balign 4
Cry_Swablu::
	.incbin "sound/direct_sound_samples/cries/swablu.bin"

	.balign 4
Cry_Altaria::
	.incbin "sound/direct_sound_samples/cries/altaria.bin"

	.balign 4
Cry_Unused265::
	.incbin "sound/direct_sound_samples/cries/unused_265.bin"

	.balign 4
Cry_Taillow::
	.incbin "sound/direct_sound_samples/cries/taillow.bin"

	.balign 4
Cry_Swellow::
	.incbin "sound/direct_sound_samples/cries/swellow.bin"

	.balign 4
Cry_Unused268::
	.incbin "sound/direct_sound_samples/cries/unused_268.bin"

	.balign 4
Cry_Spinda::
	.incbin "sound/direct_sound_samples/cries/spinda.bin"

	.balign 4
Cry_Torchic::
	.incbin "sound/direct_sound_samples/cries/torchic.bin"

	.balign 4
Cry_Combusken::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.balign 4
Cry_Blaziken::
	.incbin "sound/direct_sound_samples/cries/blaziken.bin"

	.balign 4
Cry_Treecko::
	.incbin "sound/direct_sound_samples/cries/treecko.bin"

	.balign 4
Cry_Grovyle::
	.incbin "sound/direct_sound_samples/cries/grovyle.bin"

	.balign 4
Cry_Sceptile::
	.incbin "sound/direct_sound_samples/cries/sceptile.bin"

	.balign 4
Cry_Mudkip::
	.incbin "sound/direct_sound_samples/cries/mudkip.bin"

	.balign 4
Cry_Marshtomp::
	.incbin "sound/direct_sound_samples/cries/marshtomp.bin"

	.balign 4
Cry_Swampert::
	.incbin "sound/direct_sound_samples/cries/swampert.bin"

	.balign 4
Cry_Pelipper::
	.incbin "sound/direct_sound_samples/cries/pelipper.bin"

	.balign 4
Cry_Wingull::
	.incbin "sound/direct_sound_samples/cries/wingull.bin"

	.balign 4
Cry_Banette::
	.incbin "sound/direct_sound_samples/cries/banette.bin"

	.balign 4
Cry_Shuppet::
	.incbin "sound/direct_sound_samples/cries/shuppet.bin"

	.balign 4
Cry_Lotad::
	.incbin "sound/direct_sound_samples/cries/lotad.bin"

	.balign 4
Cry_Lombre::
	.incbin "sound/direct_sound_samples/cries/lombre.bin"

	.balign 4
Cry_Ludicolo::
	.incbin "sound/direct_sound_samples/cries/ludicolo.bin"

	.balign 4
Cry_Seedot::
	.incbin "sound/direct_sound_samples/cries/seedot.bin"

	.balign 4
Cry_Nuzleaf::
	.incbin "sound/direct_sound_samples/cries/nuzleaf.bin"

	.balign 4
Cry_Shiftry::
	.incbin "sound/direct_sound_samples/cries/shiftry.bin"

	.balign 4
Cry_Carvanha::
	.incbin "sound/direct_sound_samples/cries/carvanha.bin"

	.balign 4
Cry_Wurmple::
	.incbin "sound/direct_sound_samples/cries/wurmple.bin"

	.balign 4
Cry_Silcoon::
	.incbin "sound/direct_sound_samples/cries/silcoon.bin"

	.balign 4
Cry_Beautifly::
	.incbin "sound/direct_sound_samples/cries/beautifly.bin"

	.balign 4
Cry_Cascoon::
	.incbin "sound/direct_sound_samples/cries/cascoon.bin"

	.balign 4
Cry_Dustox::
	.incbin "sound/direct_sound_samples/cries/dustox.bin"

	.balign 4
Cry_Ralts::
	.incbin "sound/direct_sound_samples/cries/ralts.bin"

	.balign 4
Cry_Kirlia::
	.incbin "sound/direct_sound_samples/cries/kirlia.bin"

	.balign 4
Cry_Gardevoir::
	.incbin "sound/direct_sound_samples/cries/gardevoir.bin"

	.balign 4
Cry_Slakoth::
	.incbin "sound/direct_sound_samples/cries/slakoth.bin"

	.balign 4
Cry_Vigoroth::
	.incbin "sound/direct_sound_samples/cries/vigoroth.bin"

	.balign 4
Cry_Slaking::
	.incbin "sound/direct_sound_samples/cries/slaking.bin"

	.balign 4
Cry_Nincada::
	.incbin "sound/direct_sound_samples/cries/nincada.bin"

	.balign 4
Cry_Ninjask::
	.incbin "sound/direct_sound_samples/cries/ninjask.bin"

	.balign 4
Cry_Shedinja::
	.incbin "sound/direct_sound_samples/cries/shedinja.bin"

	.balign 4
Cry_Makuhita::
	.incbin "sound/direct_sound_samples/cries/makuhita.bin"

	.balign 4
Cry_Hariyama::
	.incbin "sound/direct_sound_samples/cries/hariyama.bin"

	.balign 4
Cry_Nosepass::
	.incbin "sound/direct_sound_samples/cries/nosepass.bin"

	.balign 4
Cry_Glalie::
	.incbin "sound/direct_sound_samples/cries/glalie.bin"

	.balign 4
Cry_Plusle::
	.incbin "sound/direct_sound_samples/cries/plusle.bin"

	.balign 4
Cry_Minun::
	.incbin "sound/direct_sound_samples/cries/minun.bin"

	.balign 4
Cry_Surskit::
	.incbin "sound/direct_sound_samples/cries/surskit.bin"

	.balign 4
Cry_Masquerain::
	.incbin "sound/direct_sound_samples/cries/masquerain.bin"

	.balign 4
Cry_Skitty::
	.incbin "sound/direct_sound_samples/cries/skitty.bin"

	.balign 4
Cry_Delcatty::
	.incbin "sound/direct_sound_samples/cries/delcatty.bin"

	.balign 4
Cry_Gulpin::
	.incbin "sound/direct_sound_samples/cries/gulpin.bin"

	.balign 4
Cry_Swalot::
	.incbin "sound/direct_sound_samples/cries/swalot.bin"

	.balign 4
Cry_Numel::
	.incbin "sound/direct_sound_samples/cries/numel.bin"

	.balign 4
Cry_Camerupt::
	.incbin "sound/direct_sound_samples/cries/camerupt.bin"

	.balign 4
Cry_Barboach::
	.incbin "sound/direct_sound_samples/cries/barboach.bin"

	.balign 4
Cry_Whiscash::
	.incbin "sound/direct_sound_samples/cries/whiscash.bin"

	.balign 4
Cry_Corphish::
	.incbin "sound/direct_sound_samples/cries/corphish.bin"

	.balign 4
Cry_Crawdaunt::
	.incbin "sound/direct_sound_samples/cries/crawdaunt.bin"

	.balign 4
Cry_Spoink::
	.incbin "sound/direct_sound_samples/cries/spoink.bin"

	.balign 4
Cry_Grumpig::
	.incbin "sound/direct_sound_samples/cries/grumpig.bin"

	.balign 4
Cry_Trapinch::
	.incbin "sound/direct_sound_samples/cries/trapinch.bin"

	.balign 4
Cry_Vibrava::
	.incbin "sound/direct_sound_samples/cries/vibrava.bin"

	.balign 4
Cry_Flygon::
	.incbin "sound/direct_sound_samples/cries/flygon.bin"

	.balign 4
Cry_Cacnea::
	.incbin "sound/direct_sound_samples/cries/cacnea.bin"

	.balign 4
Cry_Cacturne::
	.incbin "sound/direct_sound_samples/cries/cacturne.bin"

	.balign 4
Cry_Baltoy::
	.incbin "sound/direct_sound_samples/cries/baltoy.bin"

	.balign 4
Cry_Claydol::
	.incbin "sound/direct_sound_samples/cries/claydol.bin"

	.balign 4
Cry_Lunatone::
	.incbin "sound/direct_sound_samples/cries/lunatone.bin"

	.balign 4
Cry_Solrock::
	.incbin "sound/direct_sound_samples/cries/solrock.bin"

	.balign 4
Cry_Feebas::
	.incbin "sound/direct_sound_samples/cries/feebas.bin"

	.balign 4
Cry_Milotic::
	.incbin "sound/direct_sound_samples/cries/milotic.bin"

	.balign 4
Cry_Absol::
	.incbin "sound/direct_sound_samples/cries/absol.bin"

	.balign 4
Cry_Meditite::
	.incbin "sound/direct_sound_samples/cries/meditite.bin"

	.balign 4
Cry_Medicham::
	.incbin "sound/direct_sound_samples/cries/medicham.bin"

	.balign 4
Cry_Spheal::
	.incbin "sound/direct_sound_samples/cries/spheal.bin"

	.balign 4
Cry_Sealeo::
	.incbin "sound/direct_sound_samples/cries/sealeo.bin"

	.balign 4
Cry_Walrein::
	.incbin "sound/direct_sound_samples/cries/walrein.bin"

	.balign 4
Cry_Clamperl::
	.incbin "sound/direct_sound_samples/cries/clamperl.bin"

	.balign 4
Cry_Huntail::
	.incbin "sound/direct_sound_samples/cries/huntail.bin"

	.balign 4
Cry_Gorebyss::
	.incbin "sound/direct_sound_samples/cries/gorebyss.bin"

	.balign 4
Cry_Lileep::
	.incbin "sound/direct_sound_samples/cries/lileep.bin"

	.balign 4
Cry_Cradily::
	.incbin "sound/direct_sound_samples/cries/cradily.bin"

	.balign 4
Cry_Anorith::
	.incbin "sound/direct_sound_samples/cries/anorith.bin"

	.balign 4
Cry_Armaldo::
	.incbin "sound/direct_sound_samples/cries/armaldo.bin"

	.balign 4
Cry_Beldum::
	.incbin "sound/direct_sound_samples/cries/beldum.bin"

	.balign 4
Cry_Metang::
	.incbin "sound/direct_sound_samples/cries/metang.bin"

	.balign 4
Cry_Metagross::
	.incbin "sound/direct_sound_samples/cries/metagross.bin"

	.balign 4
Cry_Bagon::
	.incbin "sound/direct_sound_samples/cries/bagon.bin"

	.balign 4
Cry_Shelgon::
	.incbin "sound/direct_sound_samples/cries/shelgon.bin"

	.balign 4
Cry_Regirock::
	.incbin "sound/direct_sound_samples/cries/regirock.bin"

	.balign 4
Cry_Regice::
	.incbin "sound/direct_sound_samples/cries/regice.bin"

	.balign 4
Cry_Registeel::
	.incbin "sound/direct_sound_samples/cries/registeel.bin"

	.balign 4
Cry_Castform::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.balign 4
Cry_Volbeat::
	.incbin "sound/direct_sound_samples/cries/volbeat.bin"

	.balign 4
Cry_Illumise::
	.incbin "sound/direct_sound_samples/cries/illumise.bin"

	.balign 4
Cry_Poochyena::
	.incbin "sound/direct_sound_samples/cries/poochyena.bin"

	.balign 4
Cry_Mightyena::
	.incbin "sound/direct_sound_samples/cries/mightyena.bin"

	.balign 4
Cry_Dusclops::
	.incbin "sound/direct_sound_samples/cries/dusclops.bin"

	.balign 4
Cry_Sableye::
	.incbin "sound/direct_sound_samples/cries/sableye.bin"

	.balign 4
Cry_Mawile::
	.incbin "sound/direct_sound_samples/cries/mawile.bin"

	.balign 4
Cry_Aron::
	.incbin "sound/direct_sound_samples/cries/aron.bin"

	.balign 4
Cry_Lairon::
	.incbin "sound/direct_sound_samples/cries/lairon.bin"

	.balign 4
Cry_Aggron::
	.incbin "sound/direct_sound_samples/cries/aggron.bin"

	.balign 4
Cry_Relicanth::
	.incbin "sound/direct_sound_samples/cries/relicanth.bin"

	.balign 4
Cry_Luvdisc::
	.incbin "sound/direct_sound_samples/cries/luvdisc.bin"

	.balign 4
Cry_Groudon::
	.incbin "sound/direct_sound_samples/cries/groudon.bin"

	.balign 4
Cry_Kyogre::
	.incbin "sound/direct_sound_samples/cries/kyogre.bin"

	.balign 4
Cry_Rayquaza::
	.incbin "sound/direct_sound_samples/cries/rayquaza.bin"

	.balign 4
Cry_Salamence::
	.incbin "sound/direct_sound_samples/cries/salamence.bin"

	.balign 4
Cry_Breloom::
	.incbin "sound/direct_sound_samples/cries/breloom.bin"

	.balign 4
Cry_Shroomish::
	.incbin "sound/direct_sound_samples/cries/shroomish.bin"

	.balign 4
Cry_Linoone::
	.incbin "sound/direct_sound_samples/cries/linoone.bin"

	.balign 4
Cry_Tropius::
	.incbin "sound/direct_sound_samples/cries/tropius.bin"

	.balign 4
Cry_Wailmer::
	.incbin "sound/direct_sound_samples/cries/wailmer.bin"

	.balign 4
Cry_Zigzagoon::
	.incbin "sound/direct_sound_samples/cries/zigzagoon.bin"

	.balign 4
Cry_Exploud::
	.incbin "sound/direct_sound_samples/cries/exploud.bin"

	.balign 4
Cry_Loudred::
	.incbin "sound/direct_sound_samples/cries/loudred.bin"

	.balign 4
Cry_Wailord::
	.incbin "sound/direct_sound_samples/cries/wailord.bin"

	.balign 4
Cry_Whismur::
	.incbin "sound/direct_sound_samples/cries/whismur.bin"

	.balign 4
Cry_Snorunt::
	.incbin "sound/direct_sound_samples/cries/snorunt.bin"

	.balign 4
Cry_Latios::
	.incbin "sound/direct_sound_samples/cries/latios.bin"

	.balign 4
Cry_Jirachi::
	.incbin "sound/direct_sound_samples/cries/jirachi.bin"

	.balign 4
Cry_Deoxys::
	.incbin "sound/direct_sound_samples/cries/deoxys.bin"

	.balign 4
Cry_Chimecho::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.balign 4
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.balign 4
DirectSoundWaveData_unknown_18::
	.incbin "sound/direct_sound_samples/unknown_18.bin"

	.balign 4
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.balign 4
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.balign 4
DirectSoundWaveData_Phoneme_1::
	.incbin "sound/direct_sound_samples/phonemes/01.bin"

	.balign 4
DirectSoundWaveData_Phoneme_2::
	.incbin "sound/direct_sound_samples/phonemes/02.bin"

	.balign 4
DirectSoundWaveData_Phoneme_3::
	.incbin "sound/direct_sound_samples/phonemes/03.bin"

	.balign 4
DirectSoundWaveData_Phoneme_4::
	.incbin "sound/direct_sound_samples/phonemes/04.bin"

	.balign 4
DirectSoundWaveData_Phoneme_5::
	.incbin "sound/direct_sound_samples/phonemes/05.bin"

	.balign 4
DirectSoundWaveData_Phoneme_6::
	.incbin "sound/direct_sound_samples/phonemes/06.bin"

	.balign 4
DirectSoundWaveData_Phoneme_7::
	.incbin "sound/direct_sound_samples/phonemes/07.bin"

	.balign 4
DirectSoundWaveData_Phoneme_8::
	.incbin "sound/direct_sound_samples/phonemes/08.bin"

	.balign 4
DirectSoundWaveData_Phoneme_9::
	.incbin "sound/direct_sound_samples/phonemes/09.bin"

	.balign 4
DirectSoundWaveData_Phoneme_10::
	.incbin "sound/direct_sound_samples/phonemes/10.bin"

	.balign 4
DirectSoundWaveData_Phoneme_11::
	.incbin "sound/direct_sound_samples/phonemes/11.bin"

	.balign 4
DirectSoundWaveData_Phoneme_12::
	.incbin "sound/direct_sound_samples/phonemes/12.bin"

	.balign 4
DirectSoundWaveData_Phoneme_13::
	.incbin "sound/direct_sound_samples/phonemes/13.bin"

	.balign 4
DirectSoundWaveData_Phoneme_14::
	.incbin "sound/direct_sound_samples/phonemes/14.bin"

	.balign 4
DirectSoundWaveData_Phoneme_15::
	.incbin "sound/direct_sound_samples/phonemes/15.bin"

	.balign 4
DirectSoundWaveData_Phoneme_16::
	.incbin "sound/direct_sound_samples/phonemes/16.bin"

	.balign 4
DirectSoundWaveData_Phoneme_17::
	.incbin "sound/direct_sound_samples/phonemes/17.bin"

	.balign 4
DirectSoundWaveData_Phoneme_18::
	.incbin "sound/direct_sound_samples/phonemes/18.bin"

	.balign 4
DirectSoundWaveData_Phoneme_19::
	.incbin "sound/direct_sound_samples/phonemes/19.bin"

	.balign 4
DirectSoundWaveData_Phoneme_20::
	.incbin "sound/direct_sound_samples/phonemes/20.bin"

	.balign 4
DirectSoundWaveData_Phoneme_21::
	.incbin "sound/direct_sound_samples/phonemes/21.bin"

	.balign 4
DirectSoundWaveData_Phoneme_22::
	.incbin "sound/direct_sound_samples/phonemes/22.bin"

	.balign 4
DirectSoundWaveData_Phoneme_23::
	.incbin "sound/direct_sound_samples/phonemes/23.bin"

	.balign 4
DirectSoundWaveData_Phoneme_24::
	.incbin "sound/direct_sound_samples/phonemes/24.bin"

	.balign 4
DirectSoundWaveData_Phoneme_25::
	.incbin "sound/direct_sound_samples/phonemes/25.bin"

	.balign 4
DirectSoundWaveData_Phoneme_26::
	.incbin "sound/direct_sound_samples/phonemes/26.bin"

	.balign 4
DirectSoundWaveData_Phoneme_27::
	.incbin "sound/direct_sound_samples/phonemes/27.bin"

	.balign 4
DirectSoundWaveData_Phoneme_28::
	.incbin "sound/direct_sound_samples/phonemes/28.bin"

	.balign 4
DirectSoundWaveData_Phoneme_29::
	.incbin "sound/direct_sound_samples/phonemes/29.bin"

	.balign 4
DirectSoundWaveData_Phoneme_30::
	.incbin "sound/direct_sound_samples/phonemes/30.bin"

	.balign 4
DirectSoundWaveData_Phoneme_31::
	.incbin "sound/direct_sound_samples/phonemes/31.bin"

	.balign 4
DirectSoundWaveData_Phoneme_32::
	.incbin "sound/direct_sound_samples/phonemes/32.bin"

	.balign 4
DirectSoundWaveData_Phoneme_33::
	.incbin "sound/direct_sound_samples/phonemes/33.bin"

	.balign 4
DirectSoundWaveData_Phoneme_34::
	.incbin "sound/direct_sound_samples/phonemes/34.bin"

	.balign 4
DirectSoundWaveData_Phoneme_35::
	.incbin "sound/direct_sound_samples/phonemes/35.bin"

	.balign 4
DirectSoundWaveData_Phoneme_36::
	.incbin "sound/direct_sound_samples/phonemes/36.bin"

	.balign 4
DirectSoundWaveData_Phoneme_37::
	.incbin "sound/direct_sound_samples/phonemes/37.bin"

	.balign 4
DirectSoundWaveData_Phoneme_38::
	.incbin "sound/direct_sound_samples/phonemes/38.bin"

	.balign 4
DirectSoundWaveData_Phoneme_39::
	.incbin "sound/direct_sound_samples/phonemes/39.bin"

	.balign 4
DirectSoundWaveData_Phoneme_40::
	.incbin "sound/direct_sound_samples/phonemes/40.bin"

	.balign 4
DirectSoundWaveData_Phoneme_41::
	.incbin "sound/direct_sound_samples/phonemes/41.bin"

	.balign 4
DirectSoundWaveData_Phoneme_42::
	.incbin "sound/direct_sound_samples/phonemes/42.bin"

	.balign 4
DirectSoundWaveData_Phoneme_43::
	.incbin "sound/direct_sound_samples/phonemes/43.bin"

	.balign 4
DirectSoundWaveData_Phoneme_44::
	.incbin "sound/direct_sound_samples/phonemes/44.bin"

	.balign 4
DirectSoundWaveData_Phoneme_45::
	.incbin "sound/direct_sound_samples/phonemes/45.bin"

	.balign 4
DirectSoundWaveData_Phoneme_46::
	.incbin "sound/direct_sound_samples/phonemes/46.bin"

	.balign 4
DirectSoundWaveData_Phoneme_47::
	.incbin "sound/direct_sound_samples/phonemes/47.bin"

	.balign 4
DirectSoundWaveData_Phoneme_48::
	.incbin "sound/direct_sound_samples/phonemes/48.bin"

	.balign 4
DirectSoundWaveData_Phoneme_49::
	.incbin "sound/direct_sound_samples/phonemes/49.bin"

	.balign 4
DirectSoundWaveData_Phoneme_50::
	.incbin "sound/direct_sound_samples/phonemes/50.bin"

	.balign 4
DirectSoundWaveData_Phoneme_51::
	.incbin "sound/direct_sound_samples/phonemes/51.bin"

	.balign 4
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.balign 4
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.balign 4
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.balign 4
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
